[package]
name = "ush"
version = "0.1.0"
authors = ["Josh Mcguigan", "Arthur Beck"]
description = "The Update SHell, created for use in a collaboratively created ARG."

[dependencies]
clap = { version = "4.0", features = ["derive"] }